northwind_dw:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_PROFILE_DBNAME') }}"
      host: "{{ env_var('DBT_PROFILE_HOST') }}"
      pass: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      port: 55432
      schema: "{{ env_var('DBT_PROFILE_SCHEMA') }}"
      threads: 1
      type: postgres
      user: postgres
  target: dev