name: DBT Workflow

on:
  workflow_dispatch:  # Trigger on manual execution
  push:
    branches:
      - main

env:
  DBT_PROFILE_DBNAME: ${{ secrets.DBT_PROFILE_DBNAME }}
  DBT_PROFILE_HOST: ${{ secrets.DBT_PROFILE_HOST }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_SCHEMA: ${{ vars.DBT_PROFILE_SCHEMA }}



jobs:
  hello:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machines

    steps:
      - name: Echo Hello World
        run: echo $DBT_PROFILE_DBNAME
